# Generated by Django 3.1.1 on 2020-09-11 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnicNumbersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_number', models.BigIntegerField(db_index=True, default=None, unique=True)),
                ('cnic_teleem_pk', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_cnic_numbers',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField(db_index=True, default=None, unique=True)),
                ('has_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='NetworkInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, null=True)),
                ('network', models.CharField(max_length=45, null=True)),
                ('province', models.CharField(max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caller.phonenumbersmodel')),
            ],
            options={
                'db_table': 'tbl_network_information',
            },
        ),
        migrations.CreateModel(
            name='LocationGenderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehsil', models.CharField(db_index=True, max_length=200, null=True)),
                ('division', models.CharField(db_index=True, max_length=200, null=True)),
                ('province', models.CharField(db_index=True, max_length=50, null=True)),
                ('gander', models.CharField(db_index=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cnic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caller.cnicnumbersmodel')),
            ],
            options={
                'db_table': 'tbl_teleem_pk_data',
            },
        ),
        migrations.CreateModel(
            name='HavingErrorNumberModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caller.phonenumbersmodel')),
            ],
            options={
                'db_table': 'tbl_failed_numbers',
            },
        ),
        migrations.CreateModel(
            name='CharaghSharedNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('facebook_user_image', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('facebook_user_profile_link', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caller.phonenumbersmodel')),
            ],
            options={
                'db_table': 'tbl_charagh_shared_number',
            },
        ),
        migrations.CreateModel(
            name='NumberDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(db_index=True, max_length=200, null=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('other_phone', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cnic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caller.cnicnumbersmodel')),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caller.phonenumbersmodel')),
            ],
            options={
                'db_table': 'tbl_number_details',
                'unique_together': {('phone_number', 'cnic')},
            },
        ),
    ]
